# Generated by Django 3.1.3 on 2020-11-21 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blog.blog'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UsersReader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='users_read',
            field=models.ManyToManyField(blank=True, through='blog.UsersReader', to=settings.AUTH_USER_MODEL),
        ),
    ]
