# Generated by Django 3.1.3 on 2020-11-21 07:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20201121_1307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersReader',
            new_name='UsersRead',
        ),
    ]
